# sdbmigrate internal environment variables
env:
    region_id:
      type: int
      value: 2
    os:
      type: str
      value: linux
    test:
      # by default type is str
      #type: str
      value: bla-bla-bla

# information about database masters and their connection info
databases:
    - name: "sdbmigrate_behave_simple"
      host: "127.0.0.1"
      port: 5432
      type: postgres
      user: "test_behave"
      password: "test_behave"